pr:
- master
- develop
- feature/*

variables:
  Configuration: Debug
  SDK:
  EOCompliance-Mac: true

jobs:
- template: analyze-and-test-template.yml
  parameters:
    platform: iOS
    modules: [ AppCenter, AppCenterAnalytics, AppCenterCrashes, AppCenterDistribute ]

- template: analyze-and-test-template.yml
  parameters:
    platform: macOS
    modules: [ AppCenter, AppCenterAnalytics, AppCenterCrashes ]

- template: analyze-and-test-template.yml
  parameters:
    platform: tvOS
    modules: [ AppCenter, AppCenterAnalytics, AppCenterCrashes ]

- template: analyze-and-test-template.yml
  parameters:
    platform: MacCatalyst
    modules: [ AppCenter, AppCenterAnalytics, AppCenterCrashes ]
